# Generated by Django 4.0.1 on 2022-01-29 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='credential', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('api_key', models.TextField(blank=True, default=None, null=True)),
                ('api_key_secret', models.TextField(blank=True, default=None, null=True)),
                ('bearer_token', models.TextField(blank=True, default=None, null=True)),
                ('access_token', models.TextField(blank=True, default=None, null=True)),
                ('access_token_secret', models.TextField(blank=True, default=None, null=True)),
                ('client_id', models.TextField(blank=True, default=None, null=True)),
                ('client_secret', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('twitter_post_id', models.PositiveIntegerField(blank=True, db_index=True, editable=False, null=True)),
                ('twitter_response', models.TextField(blank=True, default=None, null=True)),
                ('status', models.CharField(choices=[('SH', 'SCHEDULED'), ('S', 'SENT'), ('F', 'FAILED')], default='SH', max_length=2)),
                ('sent_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('schedule', models.DateTimeField(blank=True, db_index=True)),
                ('hours_from_parent', models.PositiveIntegerField(blank=True, null=True)),
                ('hours_from_now', models.PositiveIntegerField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='twitter_scheduler_app.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
